// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejjfuypykhznprttpbpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqamZ1eXB5a2h6bnBydHRwYnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mjc3MTQsImV4cCI6MjA2NTUwMzcxNH0.v8wSHnsazTdzCGV7NsBHJn-AulwtzfUUK0xyxY1QLEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);